#
# SPDX-FileCopyrightText: Copyright (c) 2026 Discotheq contributors as indicated by the @author tags
#                                 SPDX-License-Identifier: Apache-2.0
#

#quarkus.openapi-generator.codegen.spec.foojay_yml.mutiny = true
#quarkus.openapi-generator.codegen.spec.foojay_yml.base-package = org.l2x6.discotheq.api
